
export default new Map([
["src/content/blog/ai-evolution-beyond-hype.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fai-evolution-beyond-hype.mdx&astroContentModuleFlag=true")],
["src/content/blog/building-products-scale-globally.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fbuilding-products-scale-globally.mdx&astroContentModuleFlag=true")],
["src/content/blog/human-side-tech-culture.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhuman-side-tech-culture.mdx&astroContentModuleFlag=true")],
["src/content/blog/developer-tools-2025-stack.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdeveloper-tools-2025-stack.mdx&astroContentModuleFlag=true")],
["src/content/blog/pm-to-founder.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpm-to-founder.mdx&astroContentModuleFlag=true")],
["src/content/blog/meaning-tech-product.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmeaning-tech-product.mdx&astroContentModuleFlag=true")],
["src/content/blog/the-act-of-failing-forward.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fthe-act-of-failing-forward.mdx&astroContentModuleFlag=true")],
["src/content/blog/the-low-code-enterprise-shift.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fthe-low-code-enterprise-shift.mdx&astroContentModuleFlag=true")],
["src/content/blog/welcome-to-tinkbyte.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwelcome-to-tinkbyte.mdx&astroContentModuleFlag=true")],
["src/content/blog/tinkbyte-content-showcase.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftinkbyte-content-showcase.mdx&astroContentModuleFlag=true")],
["src/content/pages/about.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fabout.mdx&astroContentModuleFlag=true")],
["src/content/legal/cookie-policy.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flegal%2Fcookie-policy.mdx&astroContentModuleFlag=true")],
["src/content/pages/community.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fcommunity.mdx&astroContentModuleFlag=true")],
["src/content/newsletter/issue-1.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fnewsletter%2Fissue-1.mdx&astroContentModuleFlag=true")],
["src/content/newsletter/issue-2.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fnewsletter%2Fissue-2.mdx&astroContentModuleFlag=true")],
["src/content/pages/research.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpages%2Fresearch.mdx&astroContentModuleFlag=true")],
["src/content/legal/privacy-policy.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flegal%2Fprivacy-policy.mdx&astroContentModuleFlag=true")],
["src/content/legal/terms-of-service.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flegal%2Fterms-of-service.mdx&astroContentModuleFlag=true")],
["src/content/contact/main.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcontact%2Fmain.mdx&astroContentModuleFlag=true")]]);
		